### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
Have added a worth-mentioning fellowship program offered by web3 studios.

### CODE REVIEW

**Comment by dakshsinghrathore** [comment]
Hey Yash, I hope you are doing well !! I have added a noteworthy fellowship program inside the DEVELOPER section, hope you find my contribution worth adding and merging it !!

**Comment by yashdev9274** [comment]
hey @DSR1729 thanks you for your contribution, let me first review it then I'll let you know

**Review by dakshsinghrathore — COMMENTED** [review]
Hey @yashdev9274, I haven't found any issues in my contribution. Can you please provide me with the updates regarding my changes?

**Review by yashdev9274 — APPROVED** [review]
/lgtm

**Comment by yashdev9274** [comment]
Thanks for contribution @DSR1729 , I'm looking for more contribution from you

**Pull request merged**
